apiVersion: v1
kind: Service
metadata:
  name: srv-mariadb
  namespace: ns-gitci
  labels:
    app: hawkbit
    environment: dev
    tier: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: hawkbit
    environment: dev
    tier: db
