apiVersion: v1
kind: Service
metadata:
  name: srv-lava
  namespace: ns-gitci
  labels:
    app: lava
    environment: dev
    role: lava
    tier: backend
spec:
  ports:
    - name: receiver
      port: 5555
      targetPort: 5555
    - name: publisher
      port: 5556
      targetPort: 5556
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: lava
    environment: dev
    role: lava
    tier: backend
