kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-gitci-storage-artifacts
  namespace: ns-gitci
  labels:
    app: gitci-storage
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: vol-gitci-storage-artifacts
    fsType: ext4
