kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gitci-storage-artifacts
  namespace: ns-gitci
  labels:
    app: gitci-storage
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-gitci-storage-artifacts
