kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-gitci-repos
  namespace: ns-gitci
  labels:
    app: gitci
    role: repos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeName: pv-gitci-repos
