apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-redis-master
  namespace: ns-gitci
spec:
  template:
    metadata:
      labels:
        app: gitci
        environment: dev
        role: master
        tier: db
        service: redis
    spec:
      volumes:
        - name: 900-vol-gitci-redis-data
          persistentVolumeClaim:
            claimName: pvc-gitci-redis-data
            readOnly: false
      containers:
        - name: con-redis-master
          image: redis
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: 900-vol-gitci-redis-data
              mountPath: "/data"
              readOnly: false
