apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-storage
  namespace: ns-gitci
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gitci-storage
        environment: dev
        role: webapp
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      volumes:
        - name: 902-gitci-storage-artifacts
          persistentVolumeClaim:
            claimName: pvc-gitci-storage-artifacts
            readOnly: false
      containers:
        - name: con-gitci-storage
          image: linaroproduct/gitci-storage-container:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: 902-gitci-storage-artifacts
              mountPath: "/mnt/artifacts"
              readOnly: false
