apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-storage
  namespace: ns-gitci
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gitci-storage
        environment: dev
        role: webapp
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      volumes:
        - name: gitci-storage-google-credentials
          secret:
            secretName: storage-credentials-dev
            items:
              - key: gitci-storage-dev-google-credentials.json
                path: gitci-storage-dev-google-credentials.json
      containers:
        - name: con-gitci-storage
          image: linaroproduct/gitci-storage-container:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          volumeMounts:
            - name: gitci-storage-google-credentials
              mountPath: /srv/secrets
              readOnly: true
