apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-storage
  namespace: ns-gitci
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: simple-storage
        environment: dev
        role: webapp
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 15
      volumes:
        - name: 902-ro-gitci-storage-artifacts
          persistentVolumeClaim:
            claimName: pvc-ro-gitci-storage-artifacts
            readOnly: true
        - name: 902-rw-gitci-storage-static
          persistentVolumeClaim:
            claimName: pvc-rw-gitci-storage-static
            readOnly: false
      containers:
        - name: con-simple-storage
          image: linaroproduct/gitci-storage-container:dev
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: 902-ro-gitci-storage-artifacts
              mountPath: "/mnt/artifacts"
              readOnly: true
            - name: 902-rw-gitci-storage-static
              mountPath: "/mnt/artifacts-static"
              readOnly: false
