apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-webserver
  namespace: ns-gitci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        access: external
        app: gitci
        environment: dev
        role: webserver
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: nginx
          image: linaroproduct/gitci-nginx-container:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
